backend:
  name: git-gateway
  branch: vue-refactor

# local_backend: true

media_folder: static/uploads
public_folder: /uploads

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, es]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: 'pages'
    label: 'Pages'
    i18n:
      structure: multiple_files
    folder: 'content/pages'
    delete: false
    fields:
      - { label: Title, name: title, widget: string, i18n: true }
      - { label: Lead in, name: leadIn, widget: string, i18n: true }
      - {
          label: 'Images',
          name: 'images',
          widget: 'list',
          required: false,
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

  - name: 'tabs'
    label: 'Tabs'
    i18n:
      structure: multiple_folders
    folder: 'content/tabs'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Order Position', name: 'position', widget: 'number' }
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - {
          label: 'Image',
          name: 'imageSrc',
          widget: 'image',
          allow_multiple: false,
          required: false,
        }
      - {
          label: 'Video Source',
          name: 'iframeSrc',
          widget: 'string',
          required: false,
          i18n: true,
          hint: Supplying a video source will hide the image,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

  - name: 'partners'
    label: 'Partners'
    i18n: false
    folder: 'content/partners'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Order Position', name: 'position', widget: 'number' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image', allow_multiple: false }
      - { label: 'URL', name: 'url', widget: 'string' }
